# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - kramdown

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
title: "A Cornucopia of Ideas"
description: > # this means to ignore newlines until "email:"
   Random Musings

email: pkmandke@vt.edu
#blog logo
logo: "/assets/images/arrival_512_x_512.png"
# icon: "/assets/images/home.png" # top left
icon: "/assets/images/left-arrow.png" # <a href="https://www.flaticon.com/free-icons/left-arrow" title="left arrow icons">Left arrow icons created by Syahrul Hidayatullah - Flaticon</a>
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/vt_grad_school_bldg.jpeg"

name: 'Prathamesh Mandke'
author: 'Prathamesh Mandke'
author_image: "/assets/images/face_snap.png"

paginate:	5

url: "https://pkmandke.github.io" # the base hostname & protocol for your site
baseurl: "/blog"
#used to display twitter cards
twitter_handle: '@pkmandke'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/pkmandke
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/pkmandke
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
